export const ROUTES = {
    HOME: '/',
    USER: '/users',
    USER_ADD: '/users/add',
    USER_UPDATE: '/users/:id/edit',
    USER_DETAIL: '/users/:id/detail',
    USER_CHANGE_PASSWORD: '/users/changePassword',
    REPORT_ERROR : '/report-errors',
    ERROR_404 : '/error/404',
    ERROR_403 : '/error/403',
    ERROR_500 : '/error/500',
    CONTACT : '/contact',
    COURSES : '/courses',
    COURSES_ADD : '/courses/add',
    COURSES_DETAIL : '/courses/:id/detail',
    COURSES_UPDATE : '/courses/:courseId/edit',
    CART : '/cart',
}