export const FaqActionType = {
    UPDATE_LIST_FAQS : 'UPDATE_LIST_FAQS',
    SHOW_HIDE_FAQ: 'SHOW_HIDE_FAQ',
    GET_DETAIL_QUESTION : 'GET_DETAIL_QUESTION',
    UPDATE_LIKE_OR_DISLIKE: 'UPDATE_LIKE_OR_DISLIKE',
    GET_DETAIL_FAQ: 'GET_DETAIL_FAQ',
    CHANGE_PAGE_FAQ: 'CHANGE_PAGE_FAQ',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    SEARCH_FAQ: 'SEARCH_FAQ',
}