export const workingSurvey = {
    UPDATE_FULL_QUESTION : 'UPDATE_FULL_QUESTION',
    GET_QUESTION_FOLLOW_PAGE_NUMBER : 'GET_QUESTION_FOLLOW_PAGE_NUMBER',
    CHANGE_ANSWER_QUESTION : 'CHANGE_ANSWER_QUESTION'
}